python train.py \
    --mode train \
    --use_trans_e True \
    --out_path_aware True \
    --bf16 True \
    --state_embed_size 4096 \
    --hidden_dim 4096 \
    --max_step_length 2 \
    --evaluate_freq 1 \
    --batch_size 4096 \
    --mini_batch_size 1024 \
    --train_batch_size 16 \
    --test_batch_size 128 \
    --stater_type llama \
    --instruction_type 1 \
    --stater_path /root/autodl-tmp/huggingface/hub/models--NousResearch--Llama-2-7b-hf/snapshots/dacdfcde31297e34b19ee0e7532f29586d2c17bc \
    --stater_cache_dir "" \
    --actor_checkpoint_path "" \
    --rl_train_data_path datasets/OpenDialKG/Reason/train_type_1.json \
    --rl_valid_data_path datasets/OpenDialKG/Reason/valid_type_1.json \
    --rl_test_data_path datasets/OpenDialKG/Reason/test_type_1.json 
    